### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by StormRider1224** [GalaxySynth/Mania#1]
Crash to desktop
upon finding my first torch I tried to equip and it instantly ctd. was able to replicate efficiently.

**To Reproduce**

go to inventory then click on torch

**Expected behavior**
after clicking you now shall view the desktop

**Screenshots**
idk what to screenshot

**Modlist version**
very first one
**Did you add any additional mods?**
no

:)

**Comment by StormRider1224** [comment]
after playing a bit more I tried to open a book from the inventory and got the same ctd.

**Comment by GalaxySynth** [comment]
Fixed
